//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_salesperson.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalesPersonDBEntitiesE : DbContext
    {
        public SalesPersonDBEntitiesE()
            : base("name=SalesPersonDBEntitiesE")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommissionT> CommissionT { get; set; }
        public virtual DbSet<SalesPersonT> SalesPersonT { get; set; }
    }
}
