//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_salesperson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPersonT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesPersonT()
        {
            this.CommissionT = new HashSet<CommissionT>();
        }
    
        public int SalesPersonID { get; set; }
        public int SalesPersonNumber { get; set; }
        public string SalesPersonName { get; set; }
        public string SalesPersonPassword { get; set; }
        public string SalesPersonRegion { get; set; }
        public int SalesPersonRegisterDay { get; set; }
        public int SalesPersonRegisterMonth { get; set; }
        public int SalesPersonRegisterYear { get; set; }
        public string SalesPersonImageSrc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommissionT> CommissionT { get; set; }
    }
}
